In [ ]:
# 1这道题最后也没有完全理解

import numpy as np

f1=np.array([-23,0,-16])
f2=np.array([-75,0,0])

# 第一个错，这个fc应该和另外两个和为0，但是我的问题是，两外两个和A点和为0，然后a点和c点和为0，不应该整体相等吗
fc=f1+f2
print(-fc)
# 这里我其实不知道是不是c指向右边的，但是不用左边的原因是需要加一个左边的大小

r1=np.array([0,2,3])
r2=np.array([0,2,0])
m=np.array([0,0,-49])
# 这里就是纯正的相加为0，虽然我不知道为什么
print(-(np.cross(r1,f1)+np.cross(r2,f2)+m)) #这里正负其实我不是很会判断







[98  0 16]
[  32   69 -147]


In [ ]:
# 
import sympy as s
import matplotlib.pyplot as plt
import numpy as np
x=s.S('x')

w=0.75
a=4

# 只需要用现在用的点的v，m都等于0就行了



# 注意默认v向下，m逆时针就行
# 然后第三个点代表两个斜率交点



# 纠正1 上面一定是一半正一半负，就是只能取一个点，作为x的相距点，换了就错了
# 纠正2 上面的朝向算清楚，就是函数分析一下，
# 纠正3 就是第三个点其实就是顶点的斜率交点，有必要。必须算一下，否则不按对



3.0 - 0.75*x


: 

In [89]:
# 5
f=25
l1=8e-2
l2=1.5e-2
l3=3e-2
# 这里求扭矩还是需要单位转换的
from numpy import sin,cos,radians
alpha=44

fb=f*l1/(l2+l3)

# 不知道怎么看正负号
print(-fb,fb*(l3))

-44.44444444444444 1.3333333333333333


In [ ]:
# 6
import sympy as s


a = s.Symbol('a')
x = s.Symbol('x')

fun1 = x
fun2 = x**2



f2 = s.integrate(fun1, (x, 0, 2*a + 1))


fb = f2 * (1/3 * a + 2/3)
fa = f2 - fb



f1 = s.integrate(fun1, (x, 0, a + 1/2))
r1 = 1/3 * (a + 1/2)



q1 = fa  - f1 
print(q1)



solution = s.solve([q1], [a])
print(solution)


(2*a + 1)**2/2
-(0.333333333333333*a + 0.666666666666667)*(2*a + 1)**2/2 - (a + 0.5)**2/2 + (2*a + 1)**2/2
[(-0.500000000000000,), (0.250000000000000,)]


In [5]:
print(47/13*2)

7.230769230769231


In [4]:
# 8

w1=63
w2=45
w3=-(w1-w2)/15*12+w1
p=655


f=(w1+w3)*12/2
import sympy as s
from scipy.integrate import quad 
x=s.S('x')
w=66-2*x


def fun1(x):
    return -(w1-w2)/15*x+w1
def fun2(x):
    return (-(w1-w2)/15*x+w1)*x 
f1,_= quad(fun1, 0, 15)
m1, _ = quad(fun2, 0, 15)

# A M 
fb=(p*25*(12/13)+m1)/15
fa=f1+p*(12/13)-fb
print(fa)
# c f
f3,_=quad(fun1, 0, 12)
vc= fa-f3
print(vc)


def fun3(x):
    return ((w1-w3)/12*x+w3)*x 


# 失误1这里写成15，w2
m2,_=quad(fun3,0,12)
ma=fa*12
print(-m2+ma)
# 失误2 这里方向反了，目前来看顺时针是正
# print(mc)
# 总结思路 
# 1 A M->fb 
# 2 F->fa 
# 3 F->vc 
# 4 C M ->mc


24.423076923076678
-645.1769230769232
-3897.3230769230804


In [52]:
# 9
# 1 A M

f1=4
f2=5
l=1

import sympy as s
a=s.S('a')

fa=(f1*l+f2*l/3)/(l-a)
fc=f1+f2-fa
# a=0.5
# fa=(f1*l+f2*l/3)/(l-a)
# fc=f1+f2-fa

print(fa,fc)


# mb=fc=0
# mb=
print(s.solve([fc],[a]))

5.66666666666667/(1 - a) 9 - 5.66666666666667/(1 - a)
{a: 0.370370370370370}


In [ ]:
# 10
import numpy as np
f1=np.array([190,-177,-107])
f2=np.array([128,0,-166])
a=4


r1=(1,a,0)
r2=(1,0,0)
fb=-f1-f2
# 方向：看a点相加为0
print(fb)
# 方向：M相加为0
mb=-np.cross(r1,f1)-np.cross(r2,f2)
print(mb)




[-318  177  273]
[ 428 -273  937]
