In [7]:
# 4
import numpy as np
a=5
b=1
c=1
d=2
F1=317
F2=449
F3=590
f1=F1*np.array([-1,0,0])
f2=F2*np.array([0,1,0])
f3=F3*np.array([0,0,-1])
r1=np.array([0,0,a])
r2=np.array([0,c,a+b])
r3=np.array([-d,c,a+b])
print(-f1-f2-f3)
print(-np.cross(r1,f1)+-np.cross(r2,f2)+-np.cross(r3,f3))

[ 317 -449  590]
[3284 2765    0]


In [4]:
# 6
import sympy as s
wa=140
wb=434
x1=8
x2=3


f1=wa*(x1+x2)
f2=((wb-wa)/2*x2)
print(f1,f2)

x=s.S('x')

# x*f1=(x1/2+x2/3*2-x)*f2

f=f1+f2

r=(f1*(x1+x2)/2+(x1+x2/3*2)*f2)/f


print(f*r/(x1+x2))
print(f*(x2+x1-r)/(x1+x2))


1540 441.0
1170.909090909091
810.0909090909091


In [3]:
# 8

import sympy as s
from numpy import sqrt,radians,sin,cos

x=s.S('x')
y=s.S('y')
z=s.S('z')

F=277
alpha=28

# 1y
q1=-F*cos(radians(alpha+30))+x*sqrt(3)/2+y-z
# 1x
q2=-F*sin(radians(alpha+30))+x*cos(radians(60))
# b

q3=-z*0.15/2-0.2*x+F*cos(radians(alpha))*0.6

print(s.solve([q1,q2,q3],[x,y,z]))



{x: 469.818645270660, y: 443.674899270243, z: 703.762145053627}


In [2]:
# 9
a=610
b=298
l1=1
l2=6
l3=2
l4=4

import numpy as np
import sympy as s
from numpy import sqrt
x=s.S('x')
y=s.S('y')

q1=x/sqrt(l3**2+l4**2)*l4*l2+y*l4/sqrt(l4**2+l3**2)*l2-a*l2
q2=x/sqrt(l3**2+l4**2)*l3-y*l3/sqrt(l4**2+l3**2)-b

print(s.solve([q1,q2],[x,y]))
m=s.solve([q1,q2],[x,y])






print(m)
x=m[x]
y=m[y]
print(x*(l4)/sqrt(l4**2+l3**2)+y*(l4)/sqrt(l4**2+l3**2)-a)


r1=np.array([l1,l2,0])
f1=np.array([0,x*(-l3)/sqrt(l4**2+l3**2),x*(l4)/sqrt(l4**2+l3**2)])
print(r1,f1)
f2=np.array([0,y*(l3)/sqrt(l4**2+l3**2),y*(l4)/sqrt(l4**2+l3**2)])
print(f2)
print(np.cross(r1,f1)+np.cross(r1,f2))

{x: 674.174495216186, y: 7.82623792124901}
{x: 674.174495216186, y: 7.82623792124901}
-5.68434188608080e-13
[1 6 0] [0 -301.500000000000 603.000000000000]
[0 3.49999999999989 6.99999999999977]
[3660.00000000000 -609.999999999999 -298.000000000000]


In [1]:
# 一些矩阵运算
import numpy as np

a=np.array([0,0,1])
b=np.array([0,1,0])

print(np.cross(a,b))
print(np.dot(a,b))
####################################### ####################################### #######################################

matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])


result = np.dot(matrix1, matrix2)
print(result)


####################################### ####################################### #######################################
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])
b = np.array([3, 15, 39]).T

x = np.linalg.solve(A, b)
print(x)

####################################### ####################################### #######################################



vector = np.array([3, 4])

vector_magnitude = np.linalg.norm(vector)
print("向量的模是:", vector_magnitude)

import numpy as np
####################################### ####################################### #######################################


b = np.array([[-1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
det_b = np.linalg.det(b)

print(det_b)

[-1  0  0]
0
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[ 17. -25.  12.]
向量的模是: 5.0
6.000000000000016
